#######################
### personal bashrc ###
#######################

#export PERSONAL="$(dirname "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")")"
export PERSONAL="$HOME/src/personal"
export PATH="${PERSONAL}/bin:${PERSONAL}/lib/bash:${PATH}"

#export PAGER='vim'

######################
### the dirs array ###
######################

export DESKTOP="$HOME/Desktop"
export SRC="${HOME}/src"
export GIT="${HOME}/git"
export PIN="${HOME}/pin"
export TEMPLATES="${HOME}/Templates"

export STUFF="$DESKTOP/stuff"
export DROPBOX="${STUFF}/Dropbox"
export OBSIDIAN="${HOME}/obsidian"
export IH="${STUFF}/ih"
export BOOKS="${STUFF}/books"
export CODE="${STUFF}/code"
export LEAN="${CODE}/lean"
export GITHUB='https://github.com/notarealdeveloper'

files+=(
    [bashrc/personal]="${PERSONAL}/bashrc"
)

dirs+=(

    [personal]="${PERSONAL}"
    [personal/bin]="${PERSONAL}/bin"
    [personal/lib]="${PERSONAL}/lib"
    [personal/etc]="${PERSONAL}/etc"

    # home
    [src]="${SRC}"
    [git]="${GIT}"
    [pin]="${PIN}"
    [mine]="${GIT}/mine"
    [templates]="${TEMPLATES}"
    [Templates]="${TEMPLATES}"
    [desktop]="${DESKTOP}"
    [legacy]="${SRC}/legacy"
    [kernel]="${STUFF}/git/orgs/linux/linux"

    # git
    [doubleunix]="${GIT}/mine/doubleunix"
    [thedynamiclinker]="${GIT}/mine/thedynamiclinker"
    [hello-corporation]="${GIT}/mine/hello-corporation"
    [notarealdeveloper]="${GIT}/mine/notarealdeveloper"

    # stuff
    [stuff]="${STUFF}"
    [personal]="${PERSONAL}"
    [obsidian]="${OBSIDIAN}"
    [dropbox]="${DROPBOX}"
    [videos]="${STUFF}/videos"
    [pictures]="${STUFF}/pictures"
    [ih]="${IH}"

    # obsidian
    [sudocode]="${OBSIDIAN}/Sudocode"
    [we]="${OBSIDIAN}/We"
    [we-the-nameless]="${OBSIDIAN}/We The Nameless"

    # code
    [code]="${CODE}"
    [linux]="${CODE}/linux"
    [python]="${CODE}/python"

    # code/lean
    [lean]="${CODE}/lean"
    [leancode]="${LEAN}/code"
    [lean4]="${LEAN}/lean4"
    [mathlib]="${LEAN}/mathlib4"

    # code/nix
    [hm]="$HOME/.config/home-manager"
    [home-manager]="$HOME/.config/home-manager"

    # documents
    [documents]="${DOCUMENTS}"
    [banks]="${DOCUMENTS}/banks"
    [car]="${DOCUMENTS}/car"
    [health]="${DOCUMENTS}/health"
    [landlording]="${DOCUMENTS}/landlording"
    [resources]="${DOCUMENTS}/resources"
    [resumes]="${DOCUMENTS}/resumes"
    [taxes]="${DOCUMENTS}/taxes"

    # ranger
    [ranger]="$HOME/.config/ranger"
)

for key in src pin; do
    dir="${dirs["$key"]}"
    if [[ -d "$dir" ]]; then
        for sub in "${dir}/"*; do
            [[ ! -d "$sub" ]] && continue
            name=${sub##*/}
            root=${dir##*/}
            #name="$(basename "$sub")"
            #root="$(basename "$dir")"
            dirs+=([$name]="$dir/$name")
        done
    fi
done

# EXPERIMENTAL!
# We MAY want to automatically add slash keys for the top level of
# everything in ${dirs[@]}, or maybe just a select set of them.
# However! We would obviously like fully recursive TAB COMPLETION,
# lazily, for things that aren't in the dir keys. The latter is the
# ideal solution, but it's a bit more subtle than this.
#for key in "${!dirs[@]}"; do
#    dir="${dirs["$key"]}"
#    if [[ -d "$dir" ]]; then
#        for sub in "${dir}/"*; do
#            [[ ! -d "$sub" ]] && continue
#            name="$(basename "$sub")"
#            root="$(basename "$dir")"
#            dirs+=([$root/$name]="$dir/$name")
#        done
#    fi
#done

############
### PATH ###
############

add_to_path        "${HOME}/.local/bin"
add_to_path        "${PERSONAL}/bin/o"
add_to_path        "${PERSONAL}/lib/bash"
add_to_path        "${HOME}/.ipython/profile_default/startup"

add_to_python_path "${PERSONAL}/lib/python"

if [[ -n ${BASH_VERSION:-} && $- == *i* ]]; then
    for completion in "${PERSONAL}/lib/bash/completions"/*.sh; do
        source "$completion"
    done
fi

######################
### PATH: THE BOOK ###
######################

export WE_THE_NAMELESS="${dirs[we-the-nameless]}"

add_to_path        "$WE_THE_NAMELESS/bin"
add_to_path        "$WE_THE_NAMELESS/bin2"

if [[ -n ${BASH_VERSION:-} && $- == *i* ]]; then
    for completion in "${WE_THE_NAMELESS}/bin/completions"/*.sh; do
        source "$completion"
    done
fi

###################
### PS1 and PS2 ###
###################

if type -P emerge &>/dev/null; then
    if [[ ${EUID} == 0 ]]; then
        export PS1="${_red}root${_whi}@${_red}g${_yel}e${_cya}n${_blu}t${_pur}o${_whi}o${_blu} \w #${_end} "
    else
        export PS1="${_red}j${_yel}a${_cya}s${_blu}o${_pur}n${_whi}@${_red}g${_yel}e${_cya}n${_blu}t${_pur}o${_whi}o${_pur} \w ${_blu}\$${_end} "
    fi
fi

###############
### aliases ###
###############
alias brcp="c personal && ${EDITOR:-vim} ${PERSONAL}/etc/bashrc && source ${HOME}/.bashrc"
alias crc="c personal && ${EDITOR:-vim} ${PERSONAL}/etc/XCompose && ibus restart"
alias ccrc="cat ${PERSONAL}/etc/XCompose"

# ranger
alias r='ranger'
alias rrc="c personal && $EDITOR etc/ranger/rc.conf"
alias rrcs="c personal && $EDITOR etc/ranger/scope.sh"

# cds
alias cs='c src'
alias cn='c nix'

###################
### os specific ###
###################

is_linux && {
    export TERMINAL='gnome-terminal'
}

is_mac && {
    export CLICOLOR=1
    export LSCOLORS=ExFxBxDxCxegedabagacad
    unalias ls
    unalias grep
    alias ls='ls -GFh'
    alias grep='grep -E --color'

    # enable bash-completions on osx if we're running bash and have it installed
    is_bash && {
        if [[ -f /usr/local/etc/bash_completion ]]; then
            source /usr/local/etc/bash_completion
        fi
    }
}

set_up_pkg_config() {
    local out p sub
    deps=(zlib openssl bzip2 xz zstd libffi readline ncurses gdbm sqlite libuuid tk)
    for name in "${deps[@]}"; do
        if out="$(nix path-info --offline "nixpkgs#${name}.dev" 2>/dev/null)"; then
            for sub in lib/pkgconfig share/pkgconfig; do
                p="${out}/${sub}"
                [[ -d "$p" ]] && export PKG_CONFIG_PATH="$p:${PKG_CONFIG_PATH%:}"
            done
        fi
    done
}

###################################
### PRESENTATION SPECIFIC STUFF ###
###################################

#export PS1="\n${_gre}user${_red}@${_blu}world${_pur} \w ${_blu}\$${_end} "
if [[ ${UID} == 0 ]]; then
    export PS1="${_red}root${_whi}@${_red}world${_whi} \w ${_red}\$${_end} "
else
    export PS1="${_gre}user${_red}@${_blu}world${_pur} \w ${_blu}\$${_end} "
fi

if [[ -n $VIRTUAL_ENV ]]; then
    true
    #echo "$VIRTUAL_ENV"
else
    true
    #shopt -q login_shell || penv master
    #penv master
fi
# penv master
venv mistress

shorter_prompt # let's do this by default

next() {
    git reset --hard $(git rev-list presentation...simple | tail -1)
}

sstc() {
    sudo systemctl status cachix-daemon@notarealdeveloper.service
}
ssrc() {
    sudo systemctl restart cachix-daemon@notarealdeveloper.service
}

#unalias gl
#gl() {
#    if [[ $(basename "$PWD") == es-hf ]]; then
#        git log --color=always --name-only --shortstat --author="Jason Wilkes" presentation...simple \
#            | sed -r -e 's@(\S+)Jason Wilkes(\S+)@User@g' -e 's/notarealdeveloper@gmail.com/user@here/g'
#    else
#        git log
#    fi
#}
shorter_prompt

#################
### SUDO CODE ###
#################
export ERCHOMAI="$SRC/bbl/formats/json"      # https://github.com/notarealdeveloper/bbl

# make capslock act as escape
# EXPERIMENT: Putting this in .profile to see if that's enough
# setxkbmap -option "caps:escape"

# If running inside Guake, start in ~/Desktop
if [[ -n "$GUAKE_TAB_UUID" ]]; then
    cd ~/Desktop
fi

unset GIT_ASKPASS SSH_ASKPASS
export GIT_TERMINAL_PROMPT=1

export MPLBACKEND=qtcairo

###########################################
### WE NOW HAVE INFINITE LAPTOP POWERS! ###
###                                     ###
### THE LORD COMMAND IS LIVE FROM PHONE ###
###########################################

# So phone ssh'ed into laptop can do gui shit. Nothing new here.
export DISPLAY=:0.0

# We're gonna need more aliases boys!
alias we='c we-the-nameless'
alias m='make'
alias q='clear'
alias 🙏='codex'

n() {
  new 2 || return
  vim -c 'normal 4ggi' -c startinsert "$(
    find . -maxdepth 1 -type f -name 'TODO*' -printf '%T@ %p\n' |
      sort -nr |
      head -n 1 |
      cut -d' ' -f2-
  )"
}
