#!/bin/bash

# Only for log, die, and colors
source ~/.bashrc

declare -A things

things=(
    [email]="letshaveanadventure@gmail.com"
    [office]="Tuesdays, 1:00-3:00pm, Psych 3243"
    [address]="6563 Trigo Road, Apartment 203"
    [phone]="8054527897"
    [licenseplate]="6SVW826"
)

usage() {
    # We can optionally pass in an explanation of what went wrong.
    [[ -n "$1" ]] && log "${1}"
    cat << EOF
USAGE
    $(basename $0) [OPTIONS]

OPTIONS
    --list, -l      List all things
    --help, -h      Show this help

THINGS:
$(for f in ${!things[@]}; do echo $f; done | sort | sed -r -z 's@\n@ @g' | fold -w 70 -s | sed 's@.*@    &@g')
EOF
    exit 1
}

thing_is_available() {
    echo ${!things[*]} | sed -z -r 's@ @\n@g' | grep -cq "^${1}$"
}

list_all_things() {
    echo ${!things[*]}
    exit 0
}

show_thing () {
    local key="${1}"
    local thing="${things[$key]}"

    if ! thing_is_available "$key"; then
        die "Thing $key not in list of available things."
    fi

    printf "${thing}\n"
    printf "${thing}" | xclip -selection c
    printf "${thing}" | xclip -selection p

    exit 0
}

[[ -z "$1" ]] && usage

while [[ -n "$1" ]]; do
    case "$1" in
        -h|--help)          usage;;
        -l|--list)          list_all_things;;
        -*)                 usage "Unrecognized option: ${1}";;
        *)                  show_thing "${1}";;
    esac
    shift
done
