#!/bin/bash

# CONFIG
HOST='asciitomouth.com'
URI='/instrument/ajax/serverside.php'
POST_PARAMETERS='TYPE=click'
CONTENT_LENGTH="$(echo -n "$POST_PARAMETERS" | wc -c)"

# BUILD THAT SHIT
build_post_request() {
sed -rz -e 's@\n@\r\n@g' << EOF
POST ${URI} HTTP/1.1
Host: ${HOST}
Accept-Encoding: identity
X-Requested-With: XMLHttpRequest
Content-Length: ${CONTENT_LENGTH}
Content-Type: application/x-www-form-urlencoded

${POST_PARAMETERS}
EOF
}

# POST METHODS
do_post_openssl_grep() {
    regex="$1"
    build_post_request \
        |openssl s_client -ign_eof -connect "${HOST}":443 2>&1 \
        |tee >(grep -m1 "$regex" && killall openssl) &>/dev/null
}

do_post_openssl_quiet() {
    local TIMEOUT=1
    build_post_request \
        |openssl s_client -ign_eof -connect "${HOST}":443 2>&1 \
        |tee >(sleep "$TIMEOUT" && killall openssl) \
        | pcregrep -Mo 'HTTP/(.|\n)+'
}

do_post_openssl() {
    local TIMEOUT=1
    build_post_request \
        |openssl s_client -ign_eof -connect "${HOST}":443 2>&1 \
        |tee >(sleep "$TIMEOUT" && killall openssl)
}

do_post_socat() {
    build_post_request | socat - OPENSSL:"${HOST}":443
}

do_post_ncat() {
    build_post_request | ncat "${HOST}" 80
}

#do_post_openssl_grep "php_time"
do_post_openssl_quiet
#do_post_openssl
#do_post_socat
#do_post_ncat
