#!/usr/bin/env bash

usage() {
    [[ -n "$1" ]] && echo "${1}"
    cat << EOF
USAGE
    $(basename $0) [OPTIONS]

OPTIONS
    --help, -h      Show this help

EOF
    exit 1
}

[[ -z "$1" ]] && usage

while [[ -n "$1" ]]; do
    case "$1" in
        -h|--help)          usage;;
        *)                  usage "Unrecognized option: ${1}";;
    esac
    shift
done
